# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-18 10:32
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='Hello'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pages',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pages',
            name='slug',
            field=models.SlugField(default='', help_text='Slug will be generated automatically from the title of the post', max_length=200),
            preserve_default=False,
        ),
    ]
